{
    "config": {
        "abort": {
            "already_configured": "Dispozitivul a fost configurat deja",
            "connection_error_during_import": "S-a produs o eroare de conexiune \u00een timpul importului configura\u021biei yaml",
            "reauth_successful": "Re-autentificarea s-a realizat cu succes"
        },
        "error": {
            "connection_error": "A e\u0219uat conectarea",
            "invalid_auth": "Autentificare nevalid\u0103"
        },
        "flow_title": "Nextcloud",
        "step": {
            "reauth_confirm": {
                "data": {
                    "password": "Parola",
                    "username": "Utilizator"
                },
                "description": "Actualizeaz\u0103-\u021bi informa\u021biile de conectare pentru {url}."
            },
            "user": {
                "data": {
                    "password": "Parola",
                    "url": "URL",
                    "username": "Utilizator",
                    "verify_ssl": "Verific\u0103 certificat SSL"
                },
                "description": "Introdu informa\u021biile Nextcloud."
            }
        }
    },
    "issues": {
        "deprecated_yaml": {
            "description": "Configurarea Nextcloud folosind YAML a fost perimat\u0103.\n\nConfigura\u021bia YAML existent\u0103 a fost importat\u0103 automat \u00een interfa\u021ba grafic\u0103.\n\nElimin\u0103 configura\u021bia YAML \"nextcloud\" din fi\u0219ierul configuration.yaml \u0219i reporne\u0219te Home Assistant pentru a remedia aceast\u0103 problem\u0103.",
            "title": "Configura\u021bia Nextcloud YAML a fost perimat\u0103"
        }
    }
}